CREATE TABLE IF NOT EXISTS users (

  user_id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  f_Name VARCHAR(255) NOT NULL,
  l_Name VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  password CHAR(64) NOT NULL,
  
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
  
  );